"""
ChemGIME Configuration
======================
Central configuration constants for the ChemGIME project.
All paths are resolved relative to the project root for portability.
"""

import os
from pathlib import Path

# --- Project Root ---
# Resolved from this file's location: src/core/config.py → project root
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent

# --- Data Paths ---
DATA_DIR = PROJECT_ROOT / "data"
DB_PATH = DATA_DIR / "database"

# Pre-computed BiGG-to-SMILES mapping file (generated by scripts/create_mapping.py)
BIGG_MET_TO_SMILES_FILE = DB_PATH / "bigg_to_smiles.tsv"

# Curated cofactor SMILES list (one SMILES per line)
COFACTOR_SMILES_FILE = DB_PATH / "cofactors_smiles.txt"

# Pre-built reaction-level SMILES lookup for Gapseq .tbl standalone mode.
# Built from bigg_reactions.tbl + bigg_to_smiles.tsv by:
#   python scripts/build_bigg_rxn_smiles.py
# TSV columns: rxn | left_smiles | right_smiles
# Keys are BiGG reaction IDs (same namespace used by gapseq when the reference
# database was built from BiGG models).
BIGG_RXN_SMILES_FILE = DB_PATH / "bigg_rxn_to_smiles.tsv"

# Legacy alias — kept so any external code that imports MODELSEED_RXN_SMILES_FILE
# still works without modification.
MODELSEED_RXN_SMILES_FILE = BIGG_RXN_SMILES_FILE


def _bootstrap_bigg_rxn_smiles() -> None:
    """Build bigg_rxn_to_smiles.tsv on first use if it is missing.

    This makes the install self-healing: cloning the repo and running
    ``streamlit run src/app/main.py`` works without a manual setup step.
    Heavy work only runs once; subsequent calls are instant (file already exists).
    """
    if BIGG_RXN_SMILES_FILE.exists():
        return

    import logging
    _log = logging.getLogger(__name__)
    _log.info(
        f"{BIGG_RXN_SMILES_FILE.name} not found — building from "
        f"bigg_reactions.tbl + bigg_to_smiles.tsv …"
    )

    try:
        import subprocess, sys
        script = PROJECT_ROOT / "scripts" / "build_bigg_rxn_smiles.py"
        subprocess.run(
            [sys.executable, str(script)],
            check=True,
        )
        _log.info(f"Bootstrap complete: {BIGG_RXN_SMILES_FILE}")
    except Exception as e:
        _log.warning(
            f"Could not auto-build {BIGG_RXN_SMILES_FILE.name}: {e}  "
            "Run 'python scripts/build_bigg_rxn_smiles.py' manually."
        )

# --- Runtime Configuration ---
MAX_WORKERS = int(os.getenv("APP_MAX_WORKERS", max(1, (os.cpu_count() or 1) - 2)))

# --- Output Paths ---
REPORTS_DIR = PROJECT_ROOT / "streamlit_reports"
